
# Generated by CodiumAI
import threading
from main import start_transcription


import pytest

class TestStartTranscription:

    # Verify that the audio queue is not empty
    def test_audio_queue_not_empty(self):
        stop_flag = threading.Event()
        start_transcription(stop_flag)
        assert not stop_flag.is_set()


    # Start transcription when stop_flag is cleared
    def test_start_transcription_clear_stop_flag(self):
        stop_flag = threading.Event()
        start_transcription(stop_flag)
        assert not stop_flag.is_set()

